--DELETE FROM MEMP.DBO.IRM
--INSERT INTO MEMP.DBO.IRM
SELECT Z.IRM,
Z.ORD_NBR,
Z.TRAIN_ID,
Z.CAR_ID,
Z.CAR_CNT_ADJ,
Z.TRN_CAR_CNT,
Z.OPR_SHRT_DESC,
Z.CMPNT_POSITION,
Z.FLD_KEY,
Z.REGION,
Z.DIV,
Z.ST,
Z.STN,
Z.CST_CTR,
Z.USR,
Z.USR_FULL_NME,
Z.WRK_SHIFT,
Z.ACTVT_STRT_DT,
Z.ACTVT_STRT_TM,
Z.ACTVT_FIN_DT,
Z.ACTVT_FIN_TM,
Z.ACTVT_DUR_MIN,
Z.RPTD_HRS,
Z.RPTD_MIN,
Z.RPTD_TIME,
Z.RMV_CD,
Z.MADE,
Z.APL_CD,
Z.APL_JB_DESC,
Z.CND,
Z.RSPN,
Z.QNTY,
Z.AAR_MAT,
Z.AAR_LABOR,
Z.BILL,
Z.BILL_PER_HOUR,
Z.POTENTIAL_TIME,
Z.BILL_PER_HOUR * Z.POTENTIAL_TIME AS REVENUE,
Z.DUR_MIN_CONVERTED,
Z.CRDT_PRICE,
Z.VAR_LBR,
Z.FX_LBR,
Z.FX_LBR_STD,
Z.VAR_LBR_STD,
Z.LBR_STD,
Z.TOOL_TYPE


FROM(

SELECT Z.IRM,
Z.ORD_NBR,
Z.TRAIN_ID,
Z.CAR_ID,
Z.CAR_CNT_ADJ,
Z.TRN_CAR_CNT,
Z.OPR_SHRT_DESC,
Z.CMPNT_POSITION,
Z.FLD_KEY,
Z.REGION,
Z.DIV,
Z.ST,
Z.STN,
Z.CST_CTR,
Z.USR,
Z.USR_FULL_NME,
Z.WRK_SHIFT,
Z.ACTVT_STRT_DT,
Z.ACTVT_STRT_TM,
Z.ACTVT_FIN_DT,
Z.ACTVT_FIN_TM,
Z.ACTVT_DUR_MIN,
Z.RPTD_HRS,
Z.RPTD_MIN,
Z.RPTD_TIME,
Z.RMV_CD,
Z.MADE,
Z.APL_CD,
Z.APL_JB_DESC,
Z.CND,
Z.RSPN,
Z.QNTY,
Z.AAR_MAT,
Z.AAR_LABOR,
Z.BILL,
CASE WHEN IRM = 'Repair' AND Z.LBR_STD = '0' THEN '0'
WHEN IRM = 'Repair' AND Z.LBR_STD <> '0' THEN Z.BILL / Z.LBR_STD 
ELSE NULL
END AS BILL_PER_HOUR,
Z.LBR_STD - Z.DUR_MIN_CONVERTED AS POTENTIAL_TIME,
Z.DUR_MIN_CONVERTED,
Z.CRDT_PRICE,
Z.VAR_LBR,
Z.FX_LBR,
Z.FX_LBR_STD,
Z.VAR_LBR_STD,
Z.LBR_STD,
Z.TOOL_TYPE


FROM(
SELECT 
Z.IRM,
Z.ORD_NBR,
Z.TRAIN_ID,
Z.CAR_ID,
Z.CAR_CNT_ADJ,
Z.TRN_CAR_CNT,
Z.OPR_SHRT_DESC,
Z.CMPNT_POSITION,
Z.FLD_KEY,
Z.REGION,
Z.DIV,
Z.ST,
Z.STN,
Z.CST_CTR,
Z.USR,
Z.USR_FULL_NME,
Z.WRK_SHIFT,
Z.ACTVT_STRT_DT,
Z.ACTVT_STRT_TM,
Z.ACTVT_FIN_DT,
Z.ACTVT_FIN_TM,
Z.ACTVT_DUR_MIN,
Z.RPTD_HRS,
Z.RPTD_MIN,
Z.RPTD_TIME,
Z.RMV_CD,
Z.MADE,
Z.APL_CD,
CASE WHEN Z.APL_JB_DESC IS NULL THEN Z.AAR_STD_DESC ELSE Z.APL_JB_DESC END AS APL_JB_DESC,
Z.CND,
Z.RSPN,
Z.QNTY,
Z.AAR_MAT,
Z.AAR_LABOR,
(Z.VAR_LBR * Z.QNTY) + Z.FX_LBR - (Z.AAR_MAT + Z.CRDT_PRICE) AS BILL,
ISNULL(Z.DUR_MIN_CONVERT, 0.016) AS DUR_MIN_CONVERTED,
Z.CRDT_PRICE,
Z.VAR_LBR,
Z.FX_LBR,
Z.FX_LBR_STD,
Z.VAR_LBR_STD,
CASE WHEN Z.CALC_APPLD_QTY_HRS IS NULL AND Z.ORD_NBR LIKE '300%' THEN Z.LABOR_QTY_HRS * Z.QNTY 
WHEN Z.CALC_APPLD_QTY_HRS IS NULL AND Z.ORD_NBR LIKE '300%' AND Z.LABOR_QTY_HRS IS NULL THEN Z.DUR_MIN_CONVERT
WHEN Z.ORD_NBR NOT LIKE '300%' THEN (Z.VAR_LBR_STD * Z.QNTY) + Z.FX_LBR_STD
ELSE Z.CALC_APPLD_QTY_HRS END AS LBR_STD,
CASE WHEN Z.ORD_NBR NOT LIKE '04%' THEN 'CIR'
ELSE 'CRB'
END AS TOOL_TYPE


FROM (

SELECT *

FROM OPENQUERY(MECH_SAP, '

SELECT DISTINCT

''Repair'' AS IRM,
OPR.ORD_NBR,
CAST(NULL AS VARCHAR(15)) AS NOTIF_ID,
CAST(NULL AS VARCHAR(15)) AS TRAIN_ID,
OPR.CAR_ID,
CAST(NULL AS INT) AS CAR_CNT_ADJ,
NULL AS TRN_CAR_CNT,
CAST(NULL AS VARCHAR(15)) AS OPR_SHRT_DESC,
OPR.CMPNT_POSITION,
OPR.FLD_KEY,
OPR.REGION,
OPR.DIV,
OPR.ST,
OPR.STN,
OPR.CST_CTR_CD AS CST_CTR,
OPR.USR_ID AS USR,
OPR.USR_FULL_NME,
OPR.WRK_SHIFT,
OPR.ACTVT_STRT_DT,
OPR.ACTVT_STRT_TM,
OPR.ACTVT_FIN_DT,
OPR.ACTVT_FIN_TM,
OPR.ACTVT_DUR_MIN,
B.RPTD_HRS,
B.RPTD_MIN,
B.RPTD_HRS + (B.RPTD_MIN / 60) AS RPTD_TIME,
OPR.RMV_JB_CD AS RMV_CD,
OPR.MADE_CD AS MADE,
CAST(OPR.APL_JB_CD AS VARCHAR(10)) AS APL_CD,
CAST(OPR.APL_JB_DESC AS VARCHAR(40)) AS APL_JB_DESC,
OPR.CND_CD AS CND,
CAST(OPR.RSPN_CD AS INT) AS RSPN,
CASE WHEN OPR.APL_JB_CD IN (''N179'',''N194'') THEN OPR.QNTY / 10.00 ELSE OPR.QNTY END AS QNTY,
OPR.AAR_MAT*10 AS AAR_MAT,
OPR.AAR_LABOR *10 AS AAR_LABOR,
ROUND(ACTVT_DUR_MIN / 60,3) AS DUR_MIN_CONVERT,
A.CRDT_PRICE,
A.VAR_LBR,
A.FX_LBR,
A.FX_LBR_STD,
A.VAR_LBR_STD,
A.FX_LBR_STD + (A.VAR_LBR_STD * QNTY) AS CALC_APPLD_QTY_HRS

FROM S_CARS_ORD_OPR_RPR OPR

LEFT JOIN S_CARS_PRICE_MASTER A
ON A.APL_JB_CD = OPR.APL_JB_CD 
	AND A.RMV_JB_CD = OPR.RMV_JB_CD
	AND A.CND_CD = OPR.CND_CD
	AND A.WHY_MADE_CD = OPR.MADE_CD 
	AND A.RSP_CD = CAST(OPR.RSPN_CD AS INT)

LEFT JOIN ( 
	SELECT SUM(RPTD_HRS) AS RPTD_HRS,
		   SUM(RPTD_MIN) AS RPTD_MIN,
		   EFF_DT,
		   EMPL_SSNO
	FROM "_SYS_BIC"."bnsf.CARS.SDA/CV_VEMPL_TIME_RPTD" A

LEFT JOIN "_SYS_BIC"."bnsf.CARS.Query/QV_FLOC_ASSET" B
ON A.RESP_CTR = REPLACE(B.CST_CTR_CD,''00000'','''')
		
WHERE CAST(A.EFF_DT AS DATE) >= ''2022-05-10'' 
	AND A.UNION_CD = ''25''
	AND A.DEL_TMSTP IS NULL
	AND A.PAY_DTL_RVS = '' ''
	AND A.PAY_DTL_ADJ = '' ''
	AND B.OBJ_TYP_DESC = ''Train Yard''
	AND B.FLOC_CAT_DESC = ''CAR''
	AND B.FLOC_CRE_ID = ''S_BAT_CAR''
	AND A.BUD_COSTCD IN (''110'', ''111'', ''118'')

GROUP BY A.EFF_DT, A.RESP_CTR, B.CST_CTR_CD, A.EMPL_SSNO

)B

ON B.EFF_DT = OPR.ACTVT_STRT_DT 
AND CAST(CONCAT(''B'',REPLACE(LTRIM(REPLACE(B.EMPL_SSNO, ''99'', '' '')), '' '', ''99''))AS VARCHAR(7)) = OPR.USR_ID


WHERE OPR.ACTVT_STRT_DT >= ''2022-05-10''
	AND OPR.FLD_KEY <> ''CARDFCT''
	
')

LEFT JOIN OPENQUERY(MECH_DW, '
SELECT APPLD_JCD, AAR_STD_DESC, LABOR_QTY_HRS
FROM LOAD_TABLES_MECH_PLAN.CRB_PSEUDO_CODE_LABOR
')C

ON C.APPLD_JCD = APL_CD


UNION

SELECT Y.IRM,
Y.ORD_NBR,
Y.NOTIF_ID,
Y.TRAIN_ID,
Y.CAR_ID,
Y.CAR_CNT_ADJ,
Y.TRN_CAR_CNT,
Y.OPR_SHRT_DESC,
Y.CMPNT_POSITION,
Y.FLD_KEY,
Y.REGION,
Y.DIV,
Y.ST,
Y.STN,
Y.CST_CTR,
Y.USR,
Y.USR_FULL_NME,
Y.WRK_SHIFT,
Y.ACTVT_STRT_DT,
Y.ACTVT_STRT_TM,
Y.ACTVT_FIN_DT,
Y.ACTVT_FIN_TM,
Y.ACTVT_DUR_MIN,
Y.RPTD_HRS,
Y.RPTD_MIN,
Y.RPTD_TIME,
Y.RMV_CD,
Y.MADE,
Y.APL_CD,
Y.APL_JB_DESC,
Y.CND,
Y.RSPN,
Y.QNTY,
Y.AAR_MAT,
Y.AAR_LABOR,
Y.DUR_MIN_CONVERT,
K.CRDT_PRICE AS CRDT_PRICE,
K.VAR_LBR AS VAR_LBR, 
K.FX_LBR AS FX_LBR, 
K.FX_LBR_STD AS FX_LBR_STD,
--K.VAR_LBR_STD,
CASE WHEN Y.APPLD_JCD IN ('N179'',''N194') THEN Y.QNTY 
--	 WHEN D.APPLD_QTY_HRS = ''0'' AND PC.LABOR_QTY_HRS IS NOT NULL THEN (PC.LABOR_QTY_HRS * D.APPLD_QTY) 
	 ELSE K.VAR_LBR_STD 
	 END AS VAR_LBR_STD,
Y.CALC_APPLD_QTY_HRS,
Y.APPLD_JCD, 
Y.AAR_STD_DESC,
Y.LABOR_QTY_HRS
FROM OPENQUERY(MECH_DW,  '


SELECT DISTINCT 
''Repair'' AS IRM,
D.CAR_SET_ID AS ORD_NBR,
CAST(NULL AS VARCHAR(15)) AS NOTIF_ID,
CAST(NULL AS VARCHAR(15)) AS TRAIN_ID,
CONCAT(TRIM(D.CAR_INIT),'' '',LTRIM(D.CAR_NBR)) AS CAR_ID,
CAST(NULL AS INT) AS CAR_CNT_ADJ,
NULL AS TRN_CAR_CNT,
CAST(NULL AS VARCHAR(15)) AS OPR_SHRT_DESC,
CONCAT(D.APPLD_QLFR_CD,''-'',D.RPR_LOC_CD) AS CMPNT_POSITION,
''CARREP'' AS FLD_KEY,
J.LINE_NME AS REGION,
J.BNSF_DIV_CD AS DIV,
E.STN_ST AS ST,
TRIM(E.STN_333) AS STN,
TRIM(D.COST_CNTR) AS CST_CTR,
CAST(CONCAT(''B'',E.RPR_USERID) AS VARCHAR(7)) AS USR,
G.NAME AS USR_FULL_NME,
I.EMPL_WRK_SHFT_NBR AS WRK_SHIFT,
D.RPR_DT AS ACTVT_STRT_DT,
CAST(NULL AS TIME) AS ACTVT_STRT_TM,
CAST(NULL AS DATE) AS ACTVT_FIN_DT,
CAST(NULL AS TIME) AS ACTVT_FIN_TM,
CAST(NULL AS NUMERIC) AS ACTVT_DUR_MIN,
H.RPTD_HRS AS RPTD_HRS,
H.RPTD_MIN AS RPTD_MIN,
H.RPTD_HRS + (H.RPTD_MIN / 60) AS RPTD_TIME,
D.AAR_RMV_JCD AS RMV_CD,
D.RPR_WHY_CD AS MADE,
CAST(D.APPLD_JCD AS VARCHAR(10)) AS APL_CD,
CAST(D.AAR_STD_DESC AS VARCHAR(40)) AS APL_JB_DESC,
D.APPLD_MATL_CD AS CND,
CAST(D.RPR_RESP_CD AS INT) AS RSPN,
D.APPLD_QTY AS QNTY,
D.AAR_MATL_AMT AS AAR_MAT,
D.AAR_LBR_AMT AS AAR_LABOR,
NULL AS DUR_MIN_CONVERT,
NULL AS CRDT_PRICE,
NULL AS VAR_LBR, 
NULL AS FX_LBR, 
NULL AS FX_LBR_STD,
NULL AS VAR_LBR_STD,
--CASE WHEN D.APPLD_JCD IN (''N179'',''N194'') THEN QNTY 
--	 WHEN D.APPLD_QTY_HRS = ''0'' AND PC.LABOR_QTY_HRS IS NOT NULL THEN (PC.LABOR_QTY_HRS * D.APPLD_QTY) 
--	 ELSE D.APPLD_QTY_HRS 
--	 END AS VAR_LBR_STD,
NULL AS CALC_APPLD_QTY_HRS,
CAST(NULL AS VARCHAR(10)) AS APPLD_JCD, 
CAST(NULL AS VARCHAR(40)) AS AAR_STD_DESC,
NULL AS LABOR_QTY_HRS


FROM CWVIEWS.VCAR_REPAIR_DETAIL D

LEFT JOIN CWVIEWS.VCAR_REPAIR E
ON D.CAR_SET_ID = E.CAR_SET_ID

LEFT JOIN CWVIEWS.VME_ROLLUP_STN F
ON F.COST_CENTER = CST_CTR 

LEFT JOIN ( 
	SELECT CAST(CONCAT(''B'',EMPL_ID) AS VARCHAR(7)) AS ID
	,CONCAT(TRIM(NAME_FIRST), '' '', TRIM(NAME_LAST)) AS NAME
	FROM CWVIEWS.VAAP_EMP_DATA 
	WHERE JOB_TITLE_ID_D = ''CARMAN FREIGHT (BRC)''
)G
	ON G.ID = USR

LEFT JOIN (
	SELECT SUM(RPTD_HRS) AS RPTD_HRS,
		   SUM(RPTD_MIN) AS RPTD_MIN,
		   EFF_DT,
		   EMPL_SSNO
		   		   
FROM CWX_EXP0.VCT_EMPL_TIME_RPTD
WHERE BUD_COSTCD IN (''110'', ''111'', ''118'')
AND DEL_TMSTP IS NULL
	AND PAY_DTL_RVS = '' ''
	AND PAY_DTL_ADJ = '' ''
GROUP BY EFF_DT, ADD_USER_ID, EMPL_SSNO
)H

ON CAST(CONCAT(''B'',OREPLACE(LTRIM(OREPLACE(H.EMPL_SSNO, ''99'', '' '')), '' '', ''99''))AS VARCHAR(7)) = USR
AND H.EFF_DT = ACTVT_STRT_DT

LEFT JOIN BIVIEWS.V_LOCO_WO_EMPL_TM_RPTG_TMP I
ON I.BN_EMPL_ID = USR
AND I.LOCO_WO_EMPL_TM_RPT_DT = ACTVT_STRT_DT

LEFT JOIN LOAD_TABLES_MECH_PLAN.CRB_PSEUDO_CODE_LABOR PC
ON D.APPLD_JCD = PC.APPLD_JCD

LEFT JOIN CWVIEWS.VSTATION_MASTER_BNSF J
ON J.STN_NME = STN
AND J.STN_ST = ST




WHERE D.RPR_DT >= ''2022-05-10''
AND D.CAR_SET_ID NOT LIKE ''300%''
AND F.CAT_TYP = ''TY''

')Y

LEFT JOIN OPENQUERY(MECH_SAP, '
SELECT * 
FROM S_CARS_PRICE_MASTER
')K

ON K.APL_JB_CD = Y.APL_CD 
	AND K.RMV_JB_CD = Y.RMV_CD
	AND K.CND_CD = Y.CND
	AND K.WHY_MADE_CD = Y.MADE 
	AND K.RSP_CD = Y.RSPN

UNION

SELECT *
FROM OPENQUERY(MECH_SAP, '


SELECT 
''Misc Work'' AS IRM,
A.NOTIF_ID AS ORD_NBR,
CAST(NULL AS VARCHAR(15)) AS NOTIF_ID,
A.TRN_ID AS TRAIN_ID,
CAST(NULL AS VARCHAR(15)) AS CAR_ID,
CAST(NULL AS INT) AS CAR_CNT_ADJ,
NULL AS TRN_CAR_CNT,
CAST(NULL AS VARCHAR(15)) AS OPR_SHRT_DESC,
NULL AS CMPNT_POSITION,
A.ACTVT_GRP_CD AS FLD_KEY,
A.REGION AS Region,
A.DIV AS Division,
A.ST AS State,
A.STN AS Station,
A.CST_CTR_CD AS CST_CTR,
A.ACTVT_RPRTD_BY AS USR,
A.FUL_NME AS USR_FULL_NME,
A.WRK_SHIFT AS WRK_SHIFT,
A.ACTVT_STRT_DT,
CAST(A.ACTVT_STRT_TM AS TIME) AS ACTVT_STRT_TM,
A.ACTVT_FNSH_DT AS ACTVT_FIN_DT,
CAST(A.ACTVT_FNSH_TM AS TIME) AS ACTVT_FIN_TM,
A.ACTVT_DUR_MIN,
B.RPTD_HRS,
B.RPTD_MIN,
B.RPTD_HRS + (B.RPTD_MIN / 60) AS RPTD_TIME,
NULL AS RMV_CD,
NULL AS MADE,
A.ACTVT_SEQ_NBR AS APL_CD,
A.ACTVT_CD_TXT AS APL_JB_DESC,
NULL AS CND,
NULL AS RSPN,
NULL AS QNTY,
NULL AS AAR_MAT,
NULL AS AAR_LABOR,
ROUND(A.ACTVT_DUR_MIN / 60,3) AS DUR_MIN_CONVERT,
NULL AS CRDT_PRICE,
NULL AS VAR_LBR,
NULL AS FX_LBR,
NULL AS FX_LBR_STD,
ROUND(A.ACTVT_DUR_MIN / 60,3) AS VAR_LBR_STD,
NULL AS CALC_APPLD_QTY_HRS,
CAST(NULL AS VARCHAR(10)) AS APPLD_JCD, 
CAST(NULL AS VARCHAR(40)) AS AAR_STD_DESC,
NULL AS LABOR_QTY_HRS




FROM S_CARS_NOTIF_MISC A 

LEFT JOIN ( 
	SELECT SUM(RPTD_HRS) AS RPTD_HRS,
		   SUM(RPTD_MIN) AS RPTD_MIN,
		   EFF_DT,
		   EMPL_SSNO
	FROM "_SYS_BIC"."bnsf.CARS.SDA/CV_VEMPL_TIME_RPTD" B

LEFT JOIN "_SYS_BIC"."bnsf.CARS.Query/QV_FLOC_ASSET" C
ON B.RESP_CTR = REPLACE(C.CST_CTR_CD,''00000'','''')
		
WHERE CAST(B.EFF_DT AS DATE) >= ''2022-05-10'' 
	AND B.UNION_CD = ''25''
	AND B.DEL_TMSTP IS NULL 
	AND B.PAY_DTL_RVS = '' ''
	AND B.PAY_DTL_ADJ = '' ''
	AND C.OBJ_TYP_DESC = ''Train Yard''
	AND C.FLOC_CAT_DESC = ''CAR''
	AND C.FLOC_CRE_ID = ''S_BAT_CAR''
	AND B.BUD_COSTCD IN (''110'', ''111'', ''118'')

GROUP BY B.EFF_DT, B.RESP_CTR, C.CST_CTR_CD, B.EMPL_SSNO

)B

ON B.EFF_DT = A.ACTVT_STRT_DT 
AND CAST(CONCAT(''B'',REPLACE(LTRIM(REPLACE(B.EMPL_SSNO, ''99'', '' '')), '' '', ''99''))AS VARCHAR(7)) = A.ACTVT_RPRTD_BY


WHERE A.ACTVT_STRT_DT >= ''20220510''
AND A.WRK_SHIFT IS NOT NULL

')

UNION

SELECT *
FROM OPENQUERY(MECH_SAP, '

SELECT DISTINCT
''Inspection'' AS IRM,
A.ORD_NBR,
A.NOTIF_ID AS NOTIF_ID,
CASE WHEN C.TRN_ID IS NULL THEN SUBSTR(A.TRN_KEY,1,11) 
	ELSE C.TRN_ID 
	END AS TRAIN_ID,
--SUBSTR(A.TRN_KEY,1,11) AS TRAIN_ID,
CAST(NULL AS VARCHAR(15)) AS CAR_ID,
CASE WHEN TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN CAST(A.CAR_CNT AS INT) * 3
	ELSE CAST(A.CAR_CNT AS INT)
	END AS CAR_CNT_ADJ,
A.CAR_CNT AS TRN_CAR_CNT,
A.OPR_SHRT_DESC,
NULL AS CMPNT_POSITION,
A.FLD_KEY,
A.REGION,
A.DIV,
A.ST,
A.STN,
NULL AS CST_CTR,
A.USR_ID AS USR,
A.USR_FULL_NME,
CASE WHEN A.WRK_SHIFT IS NULL AND A.ACTVT_STRT_TM > ''06:59:59'' AND A.ACTVT_STRT_TM <= ''15:00:00'' THEN ''1''
			WHEN A.WRK_SHIFT IS NULL AND A.ACTVT_STRT_TM > ''15:00:00'' AND A.ACTVT_STRT_TM <= ''23:00:00'' THEN ''2''	
			WHEN A.WRK_SHIFT IS NULL AND A.ACTVT_STRT_TM > ''23:00:00'' AND A.ACTVT_STRT_TM <= ''23:59:59'' THEN ''3''
			WHEN A.WRK_SHIFT IS NULL AND A.ACTVT_STRT_TM >= ''00:00:00'' AND A.ACTVT_STRT_TM <= ''06:59:59'' THEN ''3''
			ELSE A.WRK_SHIFT	
			END AS WRK_SHIFT,
A.ACTVT_STRT_DT,
A.ACTVT_STRT_TM,
A.ACTVT_FIN_DT,
A.ACTVT_FIN_TM,
A.ACTVT_DUR_MIN,
B.RPTD_HRS,
B.RPTD_MIN,
B.RPTD_HRS + (B.RPTD_MIN / 60) AS RPTD_TIME,
NULL AS RMV_CD,
NULL AS MADE,
NULL AS APL_CD,
A.INSP_TYP_LCD AS APL_JB_DESC,
NULL AS CND,
NULL AS RSPN,
1 AS QNTY,
NULL AS AAR_MAT,
NULL AS AAR_LABOR,
ROUND(A.ACTVT_DUR_MIN / 60,3) AS DUR_MIN_CONVERT,
NULL AS CRDT_PRICE,
NULL AS VAR_LBR,
NULL AS FX_LBR,
NULL AS FX_LBR_STD,
NULL AS VAR_LBR_STD,
NULL AS CALC_APPLD_QTY_HRS,
NULL AS APPLD_JCD, 
A.TRN_KEY AS AAR_STD_DESC,
CASE WHEN A.INSP_TYP_LCD = ''DEST'' AND TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN CAST(A.CAR_CNT AS INT) * 3 * .025
		WHEN A.INSP_TYP_LCD = ''DEST'' THEN CAST(A.CAR_CNT AS INT) * .025 
		WHEN A.INSP_TYP_LCD = ''EH15'' THEN .025 * CAST(A.CAR_CNT AS INT)
		WHEN A.INSP_TYP_LCD = ''EH15'' AND TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN CAST(A.CAR_CNT AS INT) * 3 * .025 
		WHEN A.INSP_TYP_LCD = ''EH17'' THEN .025 * CAST(A.CAR_CNT AS INT) 
		WHEN A.INSP_TYP_LCD = ''EH17'' AND TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN CAST(A.CAR_CNT AS INT) * 3 * .025 
		WHEN A.INSP_TYP_LCD = ''C1'' THEN .025 * CAST(A.CAR_CNT AS INT)
		WHEN A.INSP_TYP_LCD = ''C1''  AND TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN CAST(A.CAR_CNT AS INT) * 3 * .025 
		WHEN A.INSP_TYP_LCD = ''C1A'' THEN .0125 * CAST(A.CAR_CNT AS INT)
		WHEN A.INSP_TYP_LCD = ''C1A'' AND TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN CAST(A.CAR_CNT AS INT) * 3 * .0125
		WHEN A.INSP_TYP_LCD = ''TRFR'' THEN .0125 * CAST(A.CAR_CNT AS INT)
		WHEN A.INSP_TYP_LCD = ''TRFR'' AND TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN CAST(A.CAR_CNT AS INT) * 3 * .0125    
		WHEN A.INSP_TYP_LCD = ''ROLL'' THEN (CAST(A.CAR_CNT AS INT) /5.0)/60.0
		WHEN A.INSP_TYP_LCD = ''ROLL'' AND TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN (CAST(A.CAR_CNT AS INT)* 3 /5.0)/60.0   
		WHEN A.INSP_TYP_LCD = ''Roll-By'' THEN (CAST(A.CAR_CNT AS INT) /5.0)/60.0 
		WHEN A.INSP_TYP_LCD = ''Roll-By'' AND TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN (CAST(A.CAR_CNT AS INT)* 3 /5.0)/60.0
		WHEN TRN_KEY LIKE ''Q%'' OR TRN_KEY LIKE ''Z%'' OR TRN_KEY LIKE ''B%'' OR TRN_KEY LIKE ''S%'' THEN CAST(A.CAR_CNT AS INT) * 3 * .025  
		ELSE CAST(A.CAR_CNT AS INT) * .025
		END AS LABOR_QTY_HRS

FROM S_CARS_ORD_OPR_INSP A


LEFT JOIN ( 
	SELECT SUM(RPTD_HRS) AS RPTD_HRS,
		   SUM(RPTD_MIN) AS RPTD_MIN,
		   EFF_DT,
		   EMPL_SSNO
	FROM "_SYS_BIC"."bnsf.CARS.SDA/CV_VEMPL_TIME_RPTD" B

LEFT JOIN "_SYS_BIC"."bnsf.CARS.Query/QV_FLOC_ASSET" C
ON B.RESP_CTR = REPLACE(C.CST_CTR_CD,''00000'','''')


		
WHERE CAST(B.EFF_DT AS DATE) >= ''2022-05-10'' 
	AND B.UNION_CD = ''25''
	AND B.DEL_TMSTP IS NULL 
	AND B.PAY_DTL_RVS = '' ''
	AND B.PAY_DTL_ADJ = '' ''
	AND C.OBJ_TYP_DESC = ''Train Yard''
	AND C.FLOC_CAT_DESC = ''CAR''
	AND C.FLOC_CRE_ID = ''S_BAT_CAR''
	AND B.BUD_COSTCD IN (''110'', ''111'', ''118'')

GROUP BY B.EFF_DT, B.RESP_CTR, C.CST_CTR_CD, B.EMPL_SSNO

)B

ON B.EFF_DT = A.ACTVT_STRT_DT 
AND CAST(CONCAT(''B'',REPLACE(LTRIM(REPLACE(B.EMPL_SSNO, ''99'', '' '')), '' '', ''99''))AS VARCHAR(7)) = A.USR_ID

LEFT JOIN (
	SELECT NOTIF_ID, TRN_ID, CAR_CNT
	FROM"_SYS_BIC"."bnsf.CARS.Query/QV_NOTIF_INSP" 
)C 

ON C.NOTIF_ID = A.NOTIF_ID

WHERE A.ACTVT_STRT_DT >= ''20220510''
AND A.TRN_KEY NOT LIKE ''GN_INSP%''
--AND A.FLD_KEY = ''CARINSP''
')

)Z
WHERE Z.RPTD_TIME IS NOT NULL
AND Z.RPTD_TIME <> '0'
--AND CAR_CNT_ADJ <> '0'
--AND ACTVT_STRT_DT = '2023-05-01'
--AND ORD_NBR = '3001466713'
)Z
)Z
