WITH PM AS(
SEL CAR_INIT,CAR_NBR,RPR_STN_333,RPR_STN_ST,RPR_DT,CAR_SET_ID,PM_JOB_CD,CAR_PART_CAR_LOC_CD,SHOP_PGM_NBR,LST_PM_DT,CUR_PM_DT,PM_JOB_CD_DESC
FROM  CWVIEWS.VSEBW_MECH_CAR_PM2PM_FAIL A    
JOIN CWVIEWS.VLOC C  
 ON A.PM_STN_333 = SUBSTR(LOC_NME,1,9)   
 AND A.PM_STN_ST = SUBSTR(LOC_NME,10,2)   
 LEFT JOIN CWVIEWS.VSEBW_MECH_CAR_GOAL D    
 ON A.PM_STN_333 = D.STN_333  
  AND A.PM_STN_ST = D.STN_ST 
  AND MTRC_ID = '1005'   
  WHERE  A.CUR_PM_DT >= CURRENT_DATE - TD_DAY_OF_YEAR(CURRENT_DATE) - 365 
  AND LOC_ID = '194'  
  )



SELECT NULL AS GOAL, SUM(DAILY) AS DAILY, SUM(WEEKLY) AS WEEKLY, SUM(MTD) AS MTD, SUM(YTD) AS YTD, SUM(PRIOR_YEAR) AS PRIOR_YEAR
FROM (

SELECT COUNT(DISTINCT CAR_NBR) AS DAILY, CAST(NULL AS FLOAT) AS WEEKLY, CAST(NULL AS FLOAT) AS MTD, CAST(NULL AS FLOAT) AS YTD,
CAST(NULL AS FLOAT) AS PRIOR_YEAR
FROM PM
WHERE CUR_PM_DT = CURRENT_DATE - 1


UNION


SELECT CAST(NULL AS FLOAT) AS DAILY, CAST(COUNT(DISTINCT CAR_NBR)AS FLOAT) / 7  AS WEEKLY, CAST(NULL AS FLOAT) AS MTD, CAST(NULL AS FLOAT) AS YTD,
CAST(NULL AS FLOAT) AS PRIOR_YEAR
FROM PM
WHERE CUR_PM_DT >= CURRENT_DATE - 7


UNION


SELECT CAST(NULL AS FLOAT) AS DAILY, CAST(NULL AS FLOAT) AS WEEKLY, CAST(COUNT(DISTINCT CAR_NBR)AS FLOAT) / (EXTRACT(DAY FROM CURRENT_DATE )) AS MTD
, CAST(NULL AS FLOAT) AS YTD,
CAST(NULL AS FLOAT) AS PRIOR_YEAR
FROM PM
WHERE CUR_PM_DT >= CURRENT_DATE - (EXTRACT(DAY FROM CURRENT_DATE ))


UNION


SELECT CAST(NULL AS FLOAT) AS DAILY, CAST(NULL AS FLOAT) AS WEEKLY,  CAST(NULL AS FLOAT) AS MTD,
CAST(COUNT(DISTINCT CAR_NBR)AS FLOAT) / TD_DAY_OF_YEAR(CURRENT_DATE) AS YTD,
CAST(NULL AS FLOAT) AS PRIOR_YEAR
FROM PM
WHERE CUR_PM_DT >= CURRENT_DATE - TD_DAY_OF_YEAR(CURRENT_DATE)


UNION


SELECT CAST(NULL AS FLOAT) AS DAILY, CAST(NULL AS FLOAT) AS WEEKLY,  CAST(NULL AS FLOAT) AS MTD,
CAST(NULL AS FLOAT) AS YTD,
CAST(COUNT(DISTINCT CAR_NBR)AS FLOAT) / 365 AS PRIOR_YEAR
FROM PM
WHERE YEAR(CUR_PM_DT) =YEAR( CURRENT_DATE) - 1


)A