SELECT *
FROM(
SELECT DISTINCT Z.TSI_ID
			 ,Z.TSI_MAINT_TS
			 ,Z.TSI_STRT_DTTM
			 ,Z.ST_DATE
			 ,Z.TSI_EXCP_CD
			 ,Z.TSI_RESP_RD
			 ,Z.TSI_DESC
			 ,Z.TSI_RSLN_DTTM
			 ,Z.TSI_ROOT_CAUS
			 ,Z.TSI_CLO_OUT_DE
			 ,Z.TSI_SDIV_NME
			 ,Z.TSI_MINE_NME
			 ,Z.TSI_TERM_NME
			 ,Z.TSI_MP
			 ,Z.TSI_WTHR_COND
			 ,Z.TSI_TRN_OWN_RD
			 ,Z.TSI_TRN_ID
			 ,Z.TSI_LCAR_CNT
			 ,Z.TSI_ECAR_CNT
			 ,Z.TSI_TRN_GTN
			 ,Z.TSI_TRN_LGTH
			 ,Z.TSI_ENGR_FINIT
			 ,Z.TSI_ENGR_MINIT
			 ,Z.TSI_ENGR_LNME
			 ,Z.TSI_CNDT_FINIT
			 ,Z.TSI_CNDT_MINIT
			 ,Z.TSI_CNDT_LNME
			 ,Z.TSI_BRKM_FINIT
			 ,Z.TSI_BRKM_MINIT
			 ,Z.TSI_LLOCO_CNT
			 ,Z.TSI_DPLOCO_CNT
			 ,Z.TSI_TDLAY_CNT
			 ,Z.TSI_BNSF_TDLAY
			 ,Z.TSI_FGN_TDLAY
			 ,Z.TSI_CLO_CD
			 ,Z.TSI_CLO_OUT_DT
			 ,Z.TSI_MP_MODFR
			 ,Z.TSI_TRN_DIR
			 ,Z.TSI_RSP_CLL_DT
			 ,Z.TSI_RSP_ARR_DT
			 ,Z.TSI_EML_SND_CD
			 ,Z.TSI_TRK_NME
			 ,Z.TSI_DOL_XCNT
			 ,Z.TSI_MAINT_ID
			 ,Z.TSI_TDLAY_DESC
			 ,Z.TSI_DETD_INIT
			 ,Z.TSI_DETD_NBR
			 ,Z.SGNL_TRBL_TKT_ID
			 ,Z.TSI_FRST_THRU_TRN_ID
			 ,Z.TSI_FRST_THRU_PASS_TS
			 ,Z.TSI_NOTE_TXT
			 ,Z.TSI_RD_TRK_CALL_TS
			 ,Z.TSI_RD_TRK_ARR_TS
			 ,Z.TSI_RD_TRK_RLSE_TS
			 ,Z.TSI_MECH_CMNT
			 ,Z.TSI_SNT_TRN_LOST_TS
			 ,Z.MECH_SINTR_LOCO_NUMB_VAL
			 ,Z.MECH_SINTR_DFCT_CAT_DESC
			 ,Z.MECH_SINTR_DFCT_TYP_DESC
			 ,Z.PRIO_TRN_DLAY_IND
			 ,Z.RMDY_TIKT_NBR
			 ,Z.ORIG_333
			 ,Z.TRN_SCH_DPT_DT
			 ,Z.LST_MAINT_TS
			 ,Z.STN_333
,RANK() OVER(PARTITION BY Z.TRN ORDER BY Z.LST_MAINT_TS DESC) AS RANK_
,Z.ID
,Z.TSI_LLOCO_SQN AS SEQ_NBR
,Z.LLOCO_INIT AS INIT
,Z.LLOCO_NBR AS NBR
,Z.LOCO_ARR_DT
,Z.LOCO_RLSE_DT
,Z.ARR_RSN_CD
,RANK() OVER(PARTITION BY Z.LOCO_INIT, Z.LOCO_NBR ORDER BY LOCO_ARR_DT DESC) AS RANK2_
,CASE WHEN Z.TSI_EXCP_CD = 'ML' THEN Z.ORIG_333
	WHEN Z.STN_333 IS NULL THEN Z.ORIG_333 	
	ELSE Z.STN_333
	END AS RSPN_INSP_LOC
,Z.SHOP_STN AS LAST_LOCO_SHOP
FROM (

SELECT *
FROM OPENQUERY(MECH_DW,'

SELECT DISTINCT TSI_ID
			 ,TSI_MAINT_TS
			 ,TSI_STRT_DTTM
			 ,CAST(TSI_STRT_DTTM AS DATE) AS ST_DATE
			 ,TSI_EXCP_CD
			 ,TSI_RESP_RD
			 ,TSI_DESC
			 ,TSI_RSLN_DTTM
			 ,TSI_ROOT_CAUS
			 ,TSI_CLO_OUT_DE
			 ,TSI_SDIV_NME
			 ,TSI_MINE_NME
			 ,TSI_TERM_NME
			 ,TSI_MP
			 ,TSI_WTHR_COND
			 ,TSI_TRN_OWN_RD
			 ,TSI_TRN_ID
			 ,TSI_LCAR_CNT
			 ,TSI_ECAR_CNT
			 ,TSI_TRN_GTN
			 ,TSI_TRN_LGTH
			 ,TSI_ENGR_FINIT
			 ,TSI_ENGR_MINIT
			 ,TSI_ENGR_LNME
			 ,TSI_CNDT_FINIT
			 ,TSI_CNDT_MINIT
			 ,TSI_CNDT_LNME
			 ,TSI_BRKM_FINIT
			 ,TSI_BRKM_MINIT
			 ,TSI_LLOCO_CNT
			 ,TSI_DPLOCO_CNT
			 ,TSI_TDLAY_CNT
			 ,TSI_BNSF_TDLAY
			 ,TSI_FGN_TDLAY
			 ,TSI_CLO_CD
			 ,TSI_CLO_OUT_DT
			 ,TSI_MP_MODFR
			 ,TSI_TRN_DIR
			 ,TSI_RSP_CLL_DT
			 ,TSI_RSP_ARR_DT
			 ,TSI_EML_SND_CD
			 ,TSI_TRK_NME
			 ,TSI_DOL_XCNT
			 ,TSI_MAINT_ID
			 ,TSI_TDLAY_DESC
			 ,TSI_DETD_INIT
			 ,TSI_DETD_NBR
			 ,SGNL_TRBL_TKT_ID
			 ,TSI_FRST_THRU_TRN_ID
			 ,TSI_FRST_THRU_PASS_TS
			 ,TSI_NOTE_TXT
			 ,TSI_RD_TRK_CALL_TS
			 ,TSI_RD_TRK_ARR_TS
			 ,TSI_RD_TRK_RLSE_TS
			 ,TSI_MECH_CMNT
			 ,TSI_SNT_TRN_LOST_TS
			 ,MECH_SINTR_LOCO_NUMB_VAL
			 ,MECH_SINTR_DFCT_CAT_DESC
			 ,MECH_SINTR_DFCT_TYP_DESC
			 ,PRIO_TRN_DLAY_IND
			 ,RMDY_TIKT_NBR
			 ,SUBSTRING(TSI_TRN_ID,1,10) AS TRN
			 ,SUBSTRING(TSI_TRN_ID,2,3) AS TRN_NAME
FROM Cwx_dpr0.vTSI_LOG A
WHERE tsi_excp_cd IN (''MC'',''D'',''ML'')
AND CAST(TSI_CLO_OUT_DT AS DATE) = CURRENT_DATE - 1

') SI
  
LEFT JOIN OPENQUERY(MECH_DB2, '
SELECT DISTINCT ORIG_333 
,TRN_SYM AS SYMBOL 
,TRN_SCH_DPT_DT 
,SET_CREATE_DT
,TRN_TYPE||TRN_SYM||TRN_SECT||TRN_DAY AS TRAIN
FROM OQ.TACT_SCH_SUM
WHERE TRN_SCH_DPT_DT < CURRENT_DATE

')DEST		
	
ON DEST.TRAIN = SI.TRN

	
LEFT JOIN OPENQUERY(MECH_DB2, '
SELECT A.TRN_SYM 
,A.STN_333
,A.LST_MAINT_TS 
,A.TRN_S
,A.TRN_
,A.INSP_START_DT
,ROW_NUMBER() OVER(PARTITION BY TRN_S ORDER BY LST_MAINT_TS DESC) AS RNK

FROM(

SELECT TRN_SYM
,STN_333
,LST_MAINT_TS
,INSP_START_DT
,TRN_TYPE||TRN_SYM||TRN_SECT||TRN_DAY||TRN_PRTY AS TRN_S
,TRN_TYPE||TRN_SYM||TRN_SECT||TRN_DAY AS TRN_

FROM OY.TOPCON_YD_TRN_SMRY

WHERE INSP_START_DT IS NOT NULL

)A

')INSP
ON INSP.TRN_S = SI.TSI_TRN_ID
AND INSP.TRN_ = DEST.TRAIN
AND INSP.LST_MAINT_TS <= SI.TSI_STRT_DTTM AND INSP.LST_MAINT_TS >= DEST.TRN_SCH_DPT_DT OR INSP.LST_MAINT_TS IS NULL

LEFT JOIN OPENQUERY(MECH_DW, '
SELECT TSI_ID AS ID
,TSI_LLOCO_SQN
,LLOCO_INIT
,LLOCO_NBR

FROM CWX_DPR0.VTSI_LEAD_LOCO
WHERE LLOCO_NBR <> '' ''
')UNIT		
	
ON UNIT.ID = SI.TSI_ID
AND SI.TSI_EXCP_CD = 'ML'

LEFT JOIN OPENQUERY(MECH_DW, '
SELECT 
STN_333 AS SHOP_STN
,TRIM(LOCO_INIT) AS LOCO_INIT
,TRIM(LOCO_NBR) AS LOCO_NBR
,LOCO_ARR_DT
,LOCO_RLSE_DT
,ARR_RSN_CD
,ROW_NUMBER() OVER(PARTITION BY LOCO_NBR ORDER BY LOCO_ARR_DT DESC) AS RNK3
FROM CWVIEWS.VSEBW_LOCO_CYCL_TM
WHERE LOCO_ARR_DT > CURRENT_DATE - 60
')SHOP
 
ON SHOP.LOCO_INIT = UNIT.LLOCO_INIT
AND SHOP.LOCO_NBR = UNIT.LLOCO_NBR
AND SHOP.LOCO_ARR_DT < SI.TSI_STRT_DTTM


)Z

)P
WHERE P.RANK_ = 1
AND P.RANK2_ = 1
ORDER BY P.TSI_ID ASC